name: uboyniy_cex
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  bloc: ^8.1.2
  boxy: ^2.1.2
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.4.1
  go_router: ^11.1.4
  google_fonts: ^6.1.0
  hydrated_bloc: ^9.1.2
  path_provider: ^2.1.1
  pretty_dio_logger: ^1.3.1
  provider: ^6.0.5

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter_gen:
  output: lib/util/gen/

flutter:
  uses-material-design: true

  assets:
    - assets/img/

